# Generated by Django 2.2.7 on 2020-07-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.CharField(default='Y', max_length=30, verbose_name='active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='modified_date')),
                ('name', models.CharField(max_length=30, verbose_name='cr_name')),
                ('code', models.CharField(max_length=30, verbose_name='cr_code')),
                ('fees', models.FloatField(verbose_name='cr_fee')),
                ('duration', models.CharField(max_length=30, verbose_name='cr_duration')),
                ('studrefs', models.ManyToManyField(related_name='courserefs', to='studreg.Student')),
            ],
            options={
                'db_table': 'Courses_Info',
            },
        ),
    ]
